const Districts = [
  // Central Region
  { code: 'BU', label: 'Buikwe' },
  { code: 'BM', label: 'Bukomansimbi' },
  { code: 'BT', label: 'Butambala' },
  { code: 'BV', label: 'Buvuma' },
  { code: 'GO', label: 'Gomba' },
  { code: 'KA', label: 'Kalangala' },
  { code: 'KG', label: 'Kalungu' },
  { code: 'KJ', label: 'Kampala' },
  { code: 'KD', label: 'Kasanda' },
  { code: 'KY', label: 'Kayunga' },
  { code: 'KB', label: 'Kiboga' },
  { code: 'KW', label: 'Kyankwanzi' },
  { code: 'KT', label: 'Kyotera' },
  { code: 'LE', label: 'Luweero' },
  { code: 'LW', label: 'Lwengo' },
  { code: 'LT', label: 'Lyantonde' },
  { code: 'MK', label: 'Masaka' },
  { code: 'MT', label: 'Mityana' },
  { code: 'MP', label: 'Mpigi' },
  { code: 'MB', label: 'Mubende' },
  { code: 'MU', label: 'Mukono' },
  { code: 'NK', label: 'Nakaseke' },
  { code: 'NS', label: 'Nakasongola' },
  { code: 'RK', label: 'Rakai' },
  { code: 'SB', label: 'Sembabule' },
  { code: 'WK', label: 'Wakiso' },

  // Eastern Region
  { code: 'BU', label: 'Bukedea' },
  { code: 'BU', label: 'Bukwo' },
  { code: 'BU', label: 'Bulambuli' },
  { code: 'BU', label: 'Busia' },
  { code: 'BU', label: 'Butaleja' },
  { code: 'KA', label: 'Kaberamaido' },
  { code: 'KA', label: 'Kaliro' },
  { code: 'KB', label: 'Kibuku' },
  { code: 'KI', label: 'Kumi' },
  { code: 'ML', label: 'Manafwa' },
  { code: 'NA', label: 'Namayingo' },
  { code: 'NG', label: 'Ngora' },
  { code: 'SER', label: 'Serere' },
  { code: 'SOR', label: 'Soroti' },
  { code: 'TOR', label: 'Tororo' },

  // Northern Region
  { code: 'AMU', label: 'Amudat' },
  { code: 'ARU', label: 'Arua' },
  { code: 'DOK', label: 'Dokolo' },
  { code: 'GUL', label: 'Gulu' },
  { code: 'KAB', label: 'Kaberamaido' },
  { code: 'KOT', label: 'Kotido' },
  { code: 'LAM', label: 'Lamwo' },
  { code: 'LIR', label: 'Lira' },
  { code: 'MOY', label: 'Moyo' },
  { code: 'NAB', label: 'Nabilatuk' },
  { code: 'NAK', label: 'Nakapiripirit' },
  { code: 'NAP', label: 'Napak' },
  { code: 'NEB', label: 'Nebbi' },
  { code: 'NWO', label: 'Nwoya' },
  { code: 'OBO', label: 'Obongi' },
  { code: 'OMO', label: 'Omoro' },
  { code: 'OTU', label: 'Otuke' },
  { code: 'OYA', label: 'Oyam' },
  { code: 'PAD', label: 'Pader' },
  { code: 'PAK', label: 'Pakwach' },
  { code: 'TER', label: 'Terego' },
  { code: 'YUM', label: 'Yumbe' },
  { code: 'ZOM', label: 'Zombo' },

  // Western Region
  { code: 'HOI', label: 'Hoima' },
  { code: 'IBA', label: 'Ibanda' },
  { code: 'ISE', label: 'Isingiro' },
  { code: 'KAB', label: 'Kabale' },
  { code: 'KAM', label: 'Kamwenge' },
  { code: 'KAN', label: 'Kanungu' },
  { code: 'KAS', label: 'Kasese' },
  { code: 'KIR', label: 'Kiruhura' },
  { code: 'KIS', label: 'Kisoro' },
  { code: 'KYE', label: 'Kyegegwa' },
  { code: 'KYO', label: 'Kyankwanzi' },
  { code: 'KYU', label: 'Kyenjojo' },
  { code: 'MAS', label: 'Masindi' },
  { code: 'MBR', label: 'Mbarara' },
  { code: 'MIT', label: 'Mitooma' },
  { code: 'NKS', label: 'Nakaseke' },
  { code: 'NKL', label: 'Nakasongola' },
  { code: 'NTU', label: 'Ntungamo' },
  { code: 'RUB', label: 'Rubanda' },
  { code: 'RUK', label: 'Rukiga' },
  { code: 'RUM', label: 'Rukungiri' },
  { code: 'SHE', label: 'Sheema' },
];

export { Districts };
